### ISSUE TITLE
deployment 'multicluster-scheduler-agent' not ready 

### ISSUE THREAD

**Issue by XiangLi0619** [admiraltyio/multicluster-service-account#14]
I am installing multicluster-scheduler v0.3.0 following the user guide.During the installation, I failed with "kubemcsa bootstrap member-cluster scheduler-cluster ".

`namespace "multicluster-service-account" already exists in source cluster "cluster1"
cluster role "service-account-import-controller-remote" already exists in source cluster "cluster1"
service account "cluster2" already exists in namespace "multicluster-service-account" in source cluster "cluster1"
cluster role binding "cluster2" already exists in source cluster "cluster1"
waiting until service account "cluster2" in namespace "multicluster-service-account" in source cluster "cluster1" has a token...
service account import "cluster1" already exists in namespace "multicluster-service-account" in target cluster "cluster2"
created secret "cluster1-token-" in namespace "multicluster-service-account" in target cluster "cluster2"
waiting until service account import "cluster1" in namespace "multicluster-service-account" in target cluster "cluster2" adopts token...
kubemcsa: error: cannot bootstrap: timeout: timed out waiting for the condition`

I tried "kubemcsa bootstrap scheduler-cluster member-cluster" and got "annotated service account import controller in target cluster "cluster1"".

After finishing installing agent, I checked but found no resources. Then I checked the pods and got following results.

`multicluster-scheduler-agent           pod-admission-controller-86c8f659d9-dzx5c                      1/1     Running   1          5m19s
multicluster-scheduler                 multicluster-scheduler-6546b48794-j7n9b                        1/1     Running   0          49m
multicluster-service-account-webhook   service-account-import-admission-controller-76f76946d9-s8qww   1/1     Running   1          46m
multicluster-service-account           service-account-import-controller-7b8586f8df-x6xbt             1/1     Running   0          8m25s`

And the deployment.

`multicluster-scheduler-agent           multicluster-scheduler-agent                  0/1     0            0           8m5s
multicluster-scheduler-agent           pod-admission-controller                      1/1     1            1           8m5s
multicluster-scheduler                 multicluster-scheduler                        1/1     1            1           52m
multicluster-service-account-webhook   service-account-import-admission-controller   1/1     1            1           48m
multicluster-service-account           service-account-import-controller             1/1     1            1           48m`

The deployment multicluster-scheduler-agent isn't deployed. I re-applied the yaml file but keep unchanged. 

Also the pod service-account-import-admission-controller in each member cluster is pending.

**Comment by adrienjt** [comment]
It's hard to say what's not working in your setup without the logs and/or the Kubernetes events. Do you know why service-account-import-admission-controller is pending in the member clusters? (but running in the scheduler cluster?)

Finally, I recommend installing multicluster-scheduler v0.4 or above, which doesn't require multicluster-service-account. Also, installation has been simplified with a Helm.

**Comment by XiangLi0619** [comment]
I found the problem results from the taint on master node so the problem is solved. I'll try v0.4. Thanks!
