### ISSUE TITLE
Error: container has runAsNonRoot and image will run as root

### ISSUE THREAD

**Issue by allamand** [admiraltyio/multicluster-service-account#2]
Hello,

Thanks for this project. I would like to test it on my own, but my psp force pods to run with runAsNonRoot, and the image seams not working with this constraint.

Is it possible to make it not need root account ?

sébastien

**Comment by adrienjt** [comment]
Bonjour Sébastien,

Thanks for trying multicluster-service-account. Neither the importer nor the automounter need to be run as root. They now run as user 1000 (1b724b5b9a2aa5f4d0f054f6d0c5bbce5d0278a9). The fix will be part of the next release. In the meantime, you can simply add this to the two pod templates in the downloaded `install.yaml`:

```yaml
securityContext:
  runAsUser: 1000
```
